version: '2'

services:
  streaming:
    image: avalonmediasystem/avalon-5.x:nginx
    build: 
      context: ./nginx
    volumes:
      - streaming:/data
    ports:
      - "1935:1935"
      - "8880:80"
