version: '2'

services:
  streaming:
    image: avalonmediasystem/avalon-5.x:wowza
    build: 
      context: ./wowza
      args:
        - WOWZA_ADMIN_PASSWORD
        - WOWZA_ADMIN_USER
        - WOWZA_LICENSE_KEY
        - WOWZA_SILENT_INSTALL_KEY
    volumes:
      - streaming:/streamfiles
    ports:
      - "1935:1935"
